/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "LIB/Stm32F466xx.h"
#include "MCAL/GPIO/GPIO_interface.h"
#include "HAL/RTC/DS1307_RTC_interface.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void DMA1_Stream7_IRQHandler(){
	while(1){}
}

int main(void)
{
	uint8_t rtc_status = ds1307_RTC_init();

    /* Loop forever */
	for(;;);
}
